# Generated by Django 3.1.3 on 2020-11-16 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=70)),
                ('descripcion', models.CharField(default='', max_length=200)),
                ('categoria', models.CharField(default='', max_length=70)),
                ('genero', models.CharField(default='', max_length=70)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
